title: Docker Registry User Interface
description: The simplest and most complete UI for your private registry!
url: https://joxit.dev/docker-registry-ui
google_analytics: UA-99119327-1
theme: jekyll-theme-cayman
author: Jones Magloire
twitter:
  username: Joxit
defaults:
  - scope:
      path: ""
    values:
      image: /screenshot.png